site_name: Papà in gioco
site_url: https://papaingioco.github.io
site_author: Stefano Cecere
site_description: 

copyright: <a href="/info/contatto">Contatti</a>

theme:
  name: material
  language: it
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  features:
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: it
  - table-reader
  - minify:
      minify_html: true
  - awesome-pages
  - social:
      cards: !ENV [CI, false]
      cards_layout_options:
        background_color: "#14608E"
        color: "#FFFFFF"

repo_url: https://github.com/papaingioco/papaingioco.github.io
edit_uri: edit/main/docs/
repo_name: papaingioco.github.io

extra_css:
  - assets/stylesheets/extra.css

extra:
  consent:
    title: Accettazione Cookie
    description: >- 
      Questo sito usa alcuni cookies per garantire la migliore esperienza di navigazione. Niente di speciale.
