site_name: In GIOCO con PAPÀ
site_url: https://ingiococonpapa.github.io
site_author: Stefano Cecere
site_description: Giornata di gioco e sensibilizzazione rivolta a bambini e ragazzi dai 5 al 18 anni

copyright: Progetto Creative Commons CC BY NC SA 4.0 - <a href="https://github.com/ingiococonpapa/ingiococonpapa.github.io">site credits</a>

theme:
  name: material
  language: it
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  features:
#    - content.action.edit
    - navigation.footer
#    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - awesome-pages
  - minify:
      minify_html: true
  - social:
      cards: !ENV [CI, false]
      cards_layout_options:
        background_color: "#14608E"
        color: "#FFFFFF"

repo_url: https://github.com/ingiococonpapa/ingiococonpapa.github.io
edit_uri: edit/main/docs/
repo_name: ingiococonpapa.github.io

extra_css:
  - assets/stylesheets/extra.css

#extra:
#  consent:
#    title: Accettazione Cookie
#    description: >- 
#      Questo sito usa alcuni cookies per garantire la migliore esperienza di navigazione. Niente di speciale.

# Page tree
#nav:
#  - Home: index.md
#  - Informazioni: about
 
